spring:
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 0
# spring:
#   data:
#     mongodb:
#       host: mongo_db
#       database: weather_database_dev
#       port: 27017
